# Generated by Django 4.1.1 on 2022-09-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-createdAt']},
        ),
    ]
